"""Generate upgrade commands for outdated or vulnerable packages."""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from dep_nudge.audit import AuditResult


@dataclass
class UpgradeCommand:
    """A pip install upgrade command for a single package."""

    package: str
    current: Optional[str]
    target: str
    reason: str  # 'outdated', 'vulnerable', or 'both'

    def __str__(self) -> str:
        return f"pip install --upgrade {self.package}=={self.target}"

    def to_dict(self) -> dict:
        return {
            "package": self.package,
            "current": self.current,
            "target": self.target,
            "reason": self.reason,
            "command": str(self),
        }


def _resolve_reason(result: AuditResult) -> str:
    outdated = result.is_outdated()
    vulnerable = result.is_vulnerable()
    if outdated and vulnerable:
        return "both"
    if vulnerable:
        return "vulnerable"
    return "outdated"


def build_upgrade_command(result: AuditResult) -> Optional[UpgradeCommand]:
    """Return an UpgradeCommand for *result* if an upgrade is warranted.

    Returns ``None`` when the package does not need attention or when no
    latest version is known.
    """
    if not result.needs_attention():
        return None

    latest = result.check.latest_version if result.check else None
    if latest is None:
        return None

    current = result.check.current_version if result.check else None
    reason = _resolve_reason(result)

    return UpgradeCommand(
        package=result.package,
        current=current,
        target=latest,
        reason=reason,
    )


def build_upgrade_commands(results: List[AuditResult]) -> List[UpgradeCommand]:
    """Return upgrade commands for all results that need attention."""
    commands = []
    for result in results:
        cmd = build_upgrade_command(result)
        if cmd is not None:
            commands.append(cmd)
    return commands


def render_upgrade_script(commands: List[UpgradeCommand]) -> str:
    """Render a shell script that upgrades all flagged packages."""
    if not commands:
        return "# No upgrades required.\n"
    lines = ["#!/bin/sh", "# Generated by dep-nudge", ""]
    for cmd in commands:
        lines.append(f"# {cmd.package}: {cmd.reason}")
        lines.append(str(cmd))
        lines.append("")
    return "\n".join(lines)
